# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  
Quote.create(saying: "You are technically correct -- the best kind of correct.", author: 'Head Bureaucrat')
Quote.create(saying: "In the game of chess, you can never let your adversary see your pieces.", author: 'Zapp Brannigan')
Quote.create(saying: "Shut up and take my money!", author: 'Fry')
Quote.create(saying: "My Manwich!", author: 'Hermes')
Quote.create(saying: "One art, please!", author: 'Dr. Zoidberg')
Quote.create(saying: "For one beautiful night I knew what it was like to be a grandmother. Subjugated, yet honored.", author: 'Dr. Zoidberg')
Quote.create(saying: "The alien mothership! If we hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.", author: 'Zapp Brannigan')
Quote.create(saying: "FIX IT! FIX IT! FIX IT! FIX IT!", author: 'Fry')
Quote.create(saying: "My instinct is to hide in this barrel, like the wily fish.", author: 'Zapp Brannigan')
Quote.create(saying: "There was nothing wrong with that food. The salt level was 10% less than a lethal dose!", author: 'Bender')
Quote.create(saying: "With a warning label this big, you know it's gotta be fun!", author: 'Hermes')
Quote.create(saying: "Robo-Puppy commencing two hour yipping session.", author: 'Robo-Puppy')
Quote.create(saying: "I've got to find a way to escape the horrible ravages of youth!", author: 'Professor Farnsworth')
Quote.create(saying: "Your music is bad and you should feel bad!", author: 'Dr. Zoidberg')
Quote.create(saying: "I don't have time for this. I have to go and buy a single piece of fruit with a coupon and then return it, making people wait behind me while I complain.", author: 'Professor Farnsworth')
Quote.create(saying: "I like being old. I don't have to talk to my parents, no one asks me to help move their stuff, I don't need to understand today's edgy TV sitcoms.", author: 'Professor Farnsworth')
Quote.create(saying: "I regret...nothing!", author: 'Hedonism Bot')
Quote.create(saying: "Kittens give Morbo gas.", author: 'Morbo')
Quote.create(saying: "The devil take this predictable colon!", author: 'Professor Farnsworth')
Quote.create(saying: 'What is this emotion you humans call "wuv"?', author: 'Ndnd')
Quote.create(saying: "While you're under the knife, you could also get an ink pouch to help you escape your enemies.", author: 'Dr. Zoidberg')
Quote.create(saying: 'I prefer programs of the genre "World\'s Blankiest Blank."', author: 'Fry')
Quote.create(saying: "Prepare the water cooler, that we may gather around it later and discuss things.", author: 'Lrrr')
Quote.create(saying: "A skunk knocked over my garbage, and suddenly all I could think of was you.", author: 'Morgan Proctor')
Quote.create(saying: "It's the Apocalypse, all right. I always knew I'd have a hand in it.", author: 'Professor Farnsworth')
Quote.create(saying: "And if you kill anyone, make sure to eat their heart to gain their courage -- their rich, tasty courage.", author: 'Professor Farnsworth')
Quote.create(saying: "I'd like to put the little bastard in a sack and toss the sack in a river and hurl the river into space", author: 'Hermes')
Quote.create(saying: "That's a calculator. I ate it to gain its power.", author: 'Hermes')
Quote.create(saying: "We're all scared -- it's the human condition. Why do youse thinks I put on this tough-guy façade?", author: 'Sal')
Quote.create(saying: "Hell hath no fury like the vast robot armies of a woman scorned.", author: 'Walt')
Quote.create(saying: "The bourgeois human is a virus on the hard drive of the working robot!", author: 'Greeting Card')
Quote.create(saying: "Up yours! Up wherever your species traditionally crams things!", author: 'Hermes')